### ISSUE TITLE
OMG - is QIDI AMS coming?

### ISSUE THREAD

**Issue by TinkerBarn** [QIDITECH/QIDIStudio#1]
Looks very nice! Especially the support for more than one plate! I asked for it in the past.

Perfect!

and it seems that the QIDI AMS is hopefully coming in near future, since you can set for each object on the plate a different filament. 

Please make me happy with it 🙏👍😄

**Comment by Hukete** [comment]
> Looks very nice! Especially the support for more than one plate! I asked for it in the past.
> 
> Perfect!
> 
> and it seems that the QIDI AMS is hopefully coming in near future, since you can set for each object on the plate a different filament.
> 
> Please make me happy with it 🙏👍😄

Good work, looking forward to it.

**Comment by designgears** [comment]
![image](https://github.com/user-attachments/assets/7ff5f26c-58ce-4347-9b1d-a65769367bcc)

**Comment by TinkerBarn** [comment]
Closed.
