### ISSUE TITLE
Prompt to transfer parameters when changing printer or filament

### ISSUE THREAD

**Issue by AndreaPro** [QIDITECH/QIDIStudio#10]
Unlike Bambu Studio and Orca Slicer where a prompt suggesting to transfer parameters different than default appears in Qidi Studio this function is not working, when changing Printer, Filament or Process presets all the changes made compared to default are lost.

**Comment by QIDITECH** [comment]
Sorry that we cannot reproduce your problem, please tell me your system and version.
