### ISSUE TITLE
Klipper console error: Unknown command:"G17" with Q1 Pro

### ISSUE THREAD

**Issue by TinkerBarn** [QIDITECH/QIDIStudio#15]
I get with different STL's after slicing in QIDI Studio Version 1.9.7.52 in Klipper console the error: `Unknown command:"G17"`
Today also one error: `Unknown command:"T8"`
Use Q1 Pro with Firmware V4.4.24

The 3D prints looks always ok. I can't see any issue. But this error message should not be there.

`00:08:01 
File opened:.cache/Switch Mount+.stl.gcode Size:1368637
00:08:01 
File selected
00:08:04 
// Run Current: 0.80A Hold Current: 0.80A
00:08:05 
// Run Current: 1.00A Hold Current: 1.00A
00:08:06 
// Run Current: 0.90A Hold Current: 0.90A
00:08:07 
// Run Current: 1.00A Hold Current: 1.00A
00:08:08 
// Run Current: 0.80A Hold Current: 0.80A
00:08:09 
// Run Current: 1.00A Hold Current: 1.00A
00:08:35 
// Run Current: 1.07A Hold Current: 1.07A
00:08:36 
// Run Current: 1.07A Hold Current: 1.07A
00:11:19 
echo: Nozzle cleared
00:12:22 
echo: Nozzle cooled
00:12:25 
// Run Current: 0.80A Hold Current: 0.80A
00:12:31 
// Run Current: 1.00A Hold Current: 1.00A
00:12:32 
// Run Current: 0.90A Hold Current: 0.90A
00:12:35 
// Run Current: 1.00A Hold Current: 1.00A
00:12:36 
// Run Current: 0.80A Hold Current: 0.80A
00:12:37 
// Run Current: 1.00A Hold Current: 1.00A
00:12:49 
// Run Current: 1.07A Hold Current: 1.07A
00:12:49 
// Run Current: 1.07A Hold Current: 1.07A
00:12:49 
// Run Current: 1.07A Hold Current: 1.07A
00:13:15 
// probe at 120.000,120.000 is z=-2.294688
00:13:18 
// probe at 120.000,120.000 is z=-2.275938
00:13:20 
// probe at 120.000,120.000 is z=-2.275781
00:13:23 
// probe at 120.000,120.000 is z=-2.274063
00:13:26 
// probe at 120.000,120.000 is z=-2.213594
00:13:26 
// Probe samples exceed tolerance. Retrying...
00:13:28 
// probe at 120.000,120.000 is z=-2.275625
00:13:31 
// probe at 120.000,120.000 is z=-2.275938
00:13:31 
// probe at 120.000,120.000 is z=-2.275938
00:13:33 
// probe at 120.000,120.000 is z=-2.312188
00:13:36 
// probe at 120.000,120.000 is z=-2.278281
00:13:38 
// probe at 120.000,120.000 is z=-2.276406
00:13:38 
// Result is z=-2.276875
00:13:38 
X:120.000 Y:120.000 Z:-2.277 E:80.000
00:13:38 
// Variable Saved
00:14:54 
// Filament width sensor Turned On
00:14:54 
// Filament width measurements cleared!
00:14:54 
// Filament dia (measured mm): 1.2
00:14:55 
// Variable Saved
00:14:55 
// Variable Saved
00:14:55 
// Variable Saved
00:14:55 
// Variable Saved
00:14:55 
echo: Last File: Switch Mount+.stl.gcode
00:14:55 
// Hyperlapse: frames started (Cycle 3 sec)
00:15:02 
**// Unknown command:"T8"**
00:15:02 
// pressure_advance: 0.035000
// pressure_advance_smooth_time: 0.030000
00:16:28 
**// Unknown command:"G17"
00:17:18 
// Unknown command:"G17"
00:18:07 
// Unknown command:"G17"
00:18:23 
// Unknown command:"G17"
00:18:41 
// Unknown command:"G17"
00:18:58 
// Unknown command:"G17"
00:19:15 
// Unknown command:"G17"
00:19:32 
// Unknown command:"G17"
00:19:50 
// Unknown command:"G17"
00:20:07 
// Unknown command:"G17"
00:20:24 
// Unknown command:"G17"
00:20:38 
// Unknown command:"G17"
00:20:51 
// Unknown command:"G17"
00:21:05 
// Unknown command:"G17"
00:21:19 
// Unknown command:"G17"**
`

**Comment by QIDITECH** [comment]
Don't worry, undefined code will be skipped and won't affect printing.
We will optimize this issue in a future release.
