### ISSUE TITLE
Feature Request - Multi bed types

### ISSUE THREAD

**Issue by WyldCFH** [QIDITECH/QIDIStudio#16]
Please add the option in the printer settings to use different types of build plates. Like Orca and Bambu allows for

<img width="468" alt="image" src="https://github.com/user-attachments/assets/20861a8b-ef3d-4d0b-921e-8b967043520b">

**Comment by QIDITECH** [comment]
OK, We will add this feature in future versions.

**Comment by WyldCFH** [comment]
> OK, We will add this feature in future versions.

That'll be awesome. Thanks

**Comment by WyldCFH** [comment]
I see this in the new version. 

Thank you!
