### ISSUE TITLE
Printing over wifi does not work!!!

### ISSUE THREAD

**Issue by TrollPlayer94** [QIDITECH/QIDIStudio#2]
Connecting the device on QidiStudio with wifi does work and the fluid menu does appear in the device tab, but when you slice a file and try to send it over wifi it simply gives you a error. Will this be fixed in the next release or is this just happening to me (never had this problem on QidiSlicer).

**Comment by QIDITECH** [comment]
Please tell me some more details. What went wrong, which model did you choose, and how did you operate? Please include a video or picture to clarify the problem.

**Comment by RCsForVetsPREZ** [comment]
> Connecting the device on QidiStudio with wifi does work and the fluid menu does appear in the device tab, but when you slice a file and try to send it over wifi it simply gives you a error. Will this be fixed in the next release or is this just happening to me (never had this problem on QidiSlicer).

Mine is doing the same

**Comment by RCsForVetsPREZ** [comment]
> > Connecting the device on QidiStudio with wifi does work and the fluid menu does appear in the device tab, but when you slice a file and try to send it over wifi it simply gives you a error. Will this be fixed in the next release or is this just happening to me (never had this problem on QidiSlicer).
> 
> Mine is doing the same

Q1 PRO. QIDI SLICER  send via wifi to print and it will time out

**Comment by QIDITECH** [comment]
Ok, we will fix this issue in the next version.

**Comment by QIDITECH** [comment]
This bug has been fixed in the latest release.

**Comment by RCsForVetsPREZ** [comment]
Ok thankyou I will try to update it again. I just did it yesterday and it
still disconnects… for now I’ve move to LAN
