### ISSUE TITLE
Network connection

### ISSUE THREAD

**Issue by janzwah** [QIDITECH/QIDIStudio#34]
unable to connect via the AWS or Aliyun server to my Fluidd page.

**Comment by QIDITECH** [comment]
Can you provide videos or pictures to describe the problem in more detail? Which specific step went wrong?

**Comment by janzwah** [comment]
<img width="1728" alt="Bildschirmfoto 2024-11-21 um 09 11 27" src="https://github.com/user-attachments/assets/dc8148c6-d8d3-49fe-9313-4dcd6ffa84fd">

The problem is, in the QIDI Studio in the linked Printer tap I only see the screen I showed in the Picture. In the QIDI Link app everything is working.

I tried both Server AWS and Aliyun, currently I use the AWS.

**Comment by QIDITECH** [comment]
The page is not redirected, it has nothing to do with the network connection, please tell us your computer's system and configuration, we will try to replicate and resolve the problem.

**Comment by janzwah** [comment]
i have a MacBook Pro with a M1 Pro processor. Currently I'm having the macOS Sequoia 15.1.1. Let me know if you need anything else.
