### ISSUE TITLE
X-Max 3 - Model image in Fluidd and printer UI is missing

### ISSUE THREAD

**Issue by melrhombus** [QIDITECH/QIDIStudio#4]
Printer: X-Max 3
Settings in QidiSlicer and QidiStudio
![image](https://github.com/user-attachments/assets/0f4c82da-ba29-4beb-88eb-d501095c8431)

The printer UI has a black box while Fluidd shows default file icon.
![image](https://github.com/user-attachments/assets/e0622cb5-3d87-41ce-8e66-67e526c48c2a)

The stl has a thumbnail encoded but it it's half the size of what QidiSlicer generates.
I attached the two sliced gcode below

[gcode_samples.zip](https://github.com/user-attachments/files/17004189/gcode_samples.zip)

**Comment by QIDITECH** [comment]
Please delete the cache in the. Cache folder.

**Comment by QIDITECH** [comment]
I'm sorry. It's my mistake. I forgot that my printer had the test version of the firmware installed.
The X-MAX 3 firmware will be updated soon.

**Comment by QIDITECH** [comment]
The X-MAX 3 firmware has been updated.
