### ISSUE TITLE
プリンターがofflineのまま

### ISSUE THREAD

**Issue by temotodakei** [QIDITECH/QIDIStudio#5]
Xplus3を使用していますがプリンターを追加すると、stanbyの表示の後すぐにofflineになって、造形開始を操作でエラーが出ます。
エクスポートしたファイルをジョブに追加して印刷は可能です。
何が原因でしょうか？

**Comment by QIDITECH** [comment]
I'm very sorry. Could you please provide me with detailed videos or pictures? I can't understand what you have expressed correctly by simply describing it in words.
