### ISSUE TITLE
Cannot run flow calibration (Coarse): v1.9.5.51 MacOS_ARM64

### ISSUE THREAD

**Issue by Xorlent** [QIDITECH/QIDIStudio#9]
Please see attached screenshot.

Selecting Coarse calibration and clicking "Calibration" gives error: "Please input valid values: 0.0 < flow ratio < 2"

- Plus 4 with stock .4mm nozzle
- Generic PETG filament profile.  Flow ratio is currently .955
- 0.20mm Standard process

Thank you
![Screenshot](https://github.com/user-attachments/assets/93432f5a-d253-4c7f-8e0f-24975e4248d2)

**Comment by QIDITECH** [comment]
OK, we will fix it in next version.

**Comment by Xorlent** [comment]
In the meantime, if any users run into bugs that prevent full functionality, I've ported the Qidi Studio X Plus 4 printer profiles to OrcaSlicer:

[https://github.com/Xorlent/Orcaslicer-Qidi-Plus-4](https://github.com/Xorlent/Orcaslicer-Qidi-Plus-4)

**Comment by QIDITECH** [comment]
Thank you very much for your sharing, we have uploaded the configuration to orca, and X-Plus4 configuration has been included in the latest V2.2.0-beta2.

**Comment by Xorlent** [comment]
> Thank you very much for your sharing, we have uploaded the configuration to orca, and X-Plus4 configuration has been included in the latest V2.2.0-beta2.

Great news, thank you!

**Comment by QIDITECH** [comment]
This bug has been fixed in the latest release.
